CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL CHECK (LENGTH(TRIM(category)) > 0)
);

CREATE UNIQUE INDEX index_product_category_lower ON product_category (LOWER(category));


CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES product_category (id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES seller (user_id) ON DELETE CASCADE,
    price INTEGER NOT NULL CHECK (price >= 0),
    name TEXT NOT NULL CHECK (LENGTH(TRIM(name)) > 0),
    description TEXT CHECK (LENGTH(TRIM(description)) > 0),
    available_count INTEGER NOT NULL CHECK (available_count >= 0) DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX index_product_seller_category_name_lower 
ON product (seller_id, category_id, (LOWER(name)));

CREATE INDEX index_product_category_id ON product (category_id);


CREATE TABLE product_picture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    picture_url TEXT NOT NULL CHECK(LENGTH(TRIM(picture_url)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
);

CREATE INDEX index_product_picture_product_id ON product_picture (product_id);


CREATE TABLE product_review (
    buyer_id BIGINT NOT NULL REFERENCES buyer (user_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    review TEXT CHECK (LENGTH(TRIM(review)) > 0),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (buyer_id, product_id)
);

CREATE INDEX index_product_review_product_id ON product_review (product_id);
CREATE INDEX index_product_review_buyer_id ON product_review (buyer_id);


CREATE TABLE promocode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL CHECK (LENGTH(TRIM(code)) > 0),
    available_category_id BIGINT REFERENCES product_category (id) ON DELETE CASCADE,
    discount SMALLINT NOT NULL CHECK (discount BETWEEN 1 AND 100),
    start_datetime TIMESTAMPTZ NOT NULL,
    end_datetime TIMESTAMPTZ NOT NULL CHECK (start_datetime < end_datetime)
);

CREATE UNIQUE INDEX index_promocode_code_upper ON promocode (UPPER(code));
