CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX index_user_login_lower ON "user" (LOWER(login));

CREATE TABLE buyer (
    user_id BIGINT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    surname TEXT,
    birth_date DATE NOT NULL,
    description TEXT,
    avatar_url TEXT,
    email TEXT NOT NULL,
    telephone TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX index_buyer_email_lower ON buyer (LOWER(email));
CREATE UNIQUE INDEX index_buyer_telephone ON buyer (telephone) WHERE telephone IS NOT NULL;

CREATE TABLE seller (
    user_id BIGINT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    avatar_url TEXT,
    email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX index_seller_name_lower ON seller (LOWER(name));
CREATE UNIQUE INDEX index_seller_email_lower ON seller (LOWER(email)) WHERE email IS NOT NULL;

CREATE TABLE pickup_point (
    user_id BIGINT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_coordinates UNIQUE (longitude, latitude)
);

CREATE INDEX index_pickup_point_coords ON pickup_point (latitude, longitude);