CREATE TABLE basket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL UNIQUE REFERENCES buyer (user_id) ON DELETE CASCADE
);

CREATE TABLE basket_product (
    basket_id BIGINT NOT NULL REFERENCES basket (id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    count INTEGER NOT NULL CHECK (count > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (basket_id, product_id)
);

CREATE INDEX index_basket_product_product_id ON basket_product (product_id);


INSERT INTO basket (buyer_id)
SELECT user_id FROM buyer
ON CONFLICT (buyer_id) DO NOTHING;


CREATE OR REPLACE FUNCTION create_basket_for_buyer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO basket (buyer_id) 
    VALUES (NEW.user_id)
    ON CONFLICT (buyer_id) DO NOTHING;
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER buyer_create_basket
AFTER INSERT ON buyer
FOR EACH ROW
EXECUTE FUNCTION create_basket_for_buyer();