CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL CHECK (LENGTH(TRIM(email)) > 0),
    password_hash TEXT NOT NULL CHECK (LENGTH(TRIM(password_hash)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX index_user_email_lower ON "user" (LOWER(email));

CREATE TABLE buyer (
    user_id BIGINT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (LENGTH(TRIM(name)) > 0),
    surname TEXT CHECK (LENGTH(TRIM(surname)) > 0),
    birth_date DATE NOT NULL,
    description TEXT CHECK (LENGTH(TRIM(description)) > 0),
    avatar_url TEXT CHECK (LENGTH(TRIM(avatar_url)) > 0),
    telephone TEXT CHECK (LENGTH(TRIM(telephone)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX index_buyer_telephone ON buyer (telephone) WHERE telephone IS NOT NULL;

CREATE TABLE seller (
    user_id BIGINT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (LENGTH(TRIM(name)) > 0),
    description TEXT CHECK (LENGTH(TRIM(description)) > 0),
    avatar_url TEXT CHECK (LENGTH(TRIM(avatar_url)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX index_seller_name_lower ON seller (LOWER(name));

CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS earthdistance;

CREATE TABLE pickup_point (
    user_id BIGINT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL CHECK (start_time < end_time),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX index_pickup_point_coords ON pickup_point USING GIST (ll_to_earth(latitude, longitude));
