-- 1. Справочник статусов заказа
CREATE TABLE order_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL UNIQUE
);

-- 2. Заказы
CREATE TABLE "order" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL REFERENCES buyer (user_id) ON DELETE CASCADE,
    order_status_id BIGINT NOT NULL REFERENCES order_status (id) ON DELETE RESTRICT,
    promocode_id BIGINT REFERENCES promocode (id) ON DELETE SET NULL,
    pickup_point_id BIGINT NOT NULL REFERENCES pickup_point (user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Индексы для таблицы order
CREATE INDEX idx_order_buyer_id ON "order" (buyer_id);
CREATE INDEX idx_order_order_status_id ON "order" (order_status_id);
CREATE INDEX idx_order_pickup_point_id ON "order" (pickup_point_id);

-- 3. Позиции заказа
CREATE TABLE order_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES "order" (id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product (id) ON DELETE RESTRICT,
    count INTEGER NOT NULL CHECK (count > 0),
    price INTEGER NOT NULL CHECK (price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Индексы для таблицы order_product
CREATE INDEX idx_order_product_order_id ON order_product (order_id);
CREATE INDEX idx_order_product_product_id ON order_product (product_id);

-- 4. Уведомления по заказам
CREATE TABLE order_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES "order" (id) ON DELETE CASCADE,
    order_status_id BIGINT NOT NULL REFERENCES order_status (id) ON DELETE RESTRICT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Индексы для таблицы order_notification
CREATE INDEX idx_order_notification_order_id ON order_notification (order_id);
CREATE INDEX idx_order_notification_order_status_id ON order_notification (order_status_id);
-- Частичный индекс для быстрого поиска только НЕПРОЧИТАННЫХ уведомлений
CREATE INDEX idx_order_notification_unread ON order_notification (order_id) WHERE is_read = FALSE;