CREATE TABLE basket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL UNIQUE REFERENCES buyer (user_id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE basket_product (
    basket_id BIGINT NOT NULL REFERENCES basket (id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    count INTEGER NOT NULL CHECK (count > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (basket_id, product_id)
);

CREATE INDEX index_basket_product_product_id ON basket_product (product_id);


INSERT INTO basket (buyer_id)
SELECT user_id FROM buyer
ON CONFLICT (buyer_id) DO NOTHING;


CREATE OR REPLACE FUNCTION create_basket_for_buyer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO basket (buyer_id) 
    VALUES (NEW.user_id)
    ON CONFLICT (buyer_id) DO NOTHING;
    
    RETURN NEW;
END;
$$;

CREATE TRIGGER buyer_create_basket
AFTER INSERT ON buyer
FOR EACH ROW
EXECUTE FUNCTION create_basket_for_buyer();


CREATE OR REPLACE FUNCTION update_basket_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE basket
    SET updated_at = NOW()
    WHERE id = COALESCE(NEW.basket_id, OLD.basket_id);

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER basket_product_update_basket_updated_at
AFTER INSERT OR UPDATE OR DELETE ON basket_product
FOR EACH ROW
EXECUTE FUNCTION update_basket_updated_at();
